// Languages and UI texts.
//
// The language follows the course (`language:` in the LiaScript header, which
// LiaScript sets as <html lang>). All languages Scratch supports are
// available; English is the default. UI texts come from Scratch's own
// translations (src/locales.json, generated by `npm run gen`); the few texts
// Scratch does not have are written here, other languages fall back to English.

import locales from './locales.json'

type Locale = { ui: Record<string, string>; pen: Record<string, string>; words: Record<string, string> }

export const LOCALES = locales as Record<string, Locale>
export const LANGUAGES = Object.keys(LOCALES)
export type Lang = string

const OWN = {
  en: {
    ok: 'OK',
    cancel: 'Cancel',
    makeBlock: 'Make a Block',
    addInput: 'Add an input (number or text)',
    addBoolean: 'Add an input (boolean)',
    addLabel: 'Add a label',
    runWithoutRefresh: 'Run without screen refresh',
    stage: 'Stage',
    addSprite: 'Choose a Sprite',
    deleteSprite: 'delete',
    fullscreen: 'Full screen',
    saveSb3: 'Save sb3',
    loadSb3: 'Load sb3',
    text: 'Text',
    textError: 'The text in the code block contains an error:',
    passed: 'Well done!',
    failed: 'Not quite yet:',
    checkError: 'Error in the check:',
    line: 'Line %1',
    unknownBlock: 'unknown block “%1”',
    unknownCustomBlock: 'unknown custom block “%1”',
    unknownCostume: 'there is no costume “%1”',
    unknownSprite: 'there is no sprite “%1”',
    unknownVariable: 'there is no variable “%1”',
    notANumber: '“%1” is not a number',
    yes: 'yes',
    no: 'no',
  },
  de: {
    fullscreen: 'Vollbild',
    saveSb3: 'sb3 speichern',
    loadSb3: 'sb3 laden',
    text: 'Text',
    textError: 'Der Text im Codeblock enthält einen Fehler:',
    passed: 'Geschafft!',
    failed: 'Noch nicht ganz:',
    checkError: 'Fehler in der Prüfung:',
    line: 'Zeile %1',
    unknownBlock: 'unbekannter Block „%1“',
    unknownCustomBlock: 'unbekannter eigener Block „%1“',
    unknownCostume: 'das Kostüm „%1“ gibt es nicht',
    unknownSprite: 'die Figur „%1“ gibt es nicht',
    unknownVariable: 'die Variable „%1“ gibt es nicht',
    notANumber: '„%1“ ist keine Zahl',
    yes: 'ja',
    no: 'nein',
  },
} as Record<string, Record<string, string>>

export type Key = keyof typeof OWN.en

/** Maps a language tag (e.g. "de-AT", "pt-BR", "zh") to a supported one. */
export function resolveLang(tag: string | null | undefined): Lang {
  const code = (tag || '').trim().replace(/_/g, '-').toLowerCase()
  if (!code) return 'en'
  const exact = LANGUAGES.find((l) => l.toLowerCase() === code)
  if (exact) return exact
  const base = code.split('-')[0]
  if (base === 'zh') return code.includes('tw') || code.includes('hant') ? 'zh-tw' : 'zh-cn'
  if (base === 'pt' && code.includes('br')) return 'pt-br'
  if (base === 'es' && code !== 'es' && !code.startsWith('es-es')) return LANGUAGES.includes('es-419') ? 'es-419' : 'es'
  if (base === 'no') return 'nb'
  return LANGUAGES.find((l) => l.toLowerCase() === base) ?? 'en'
}

/** The language of the current course. */
export function lang(): Lang {
  return resolveLang(typeof document !== 'undefined' ? document.documentElement.lang : 'en')
}

export function t(key: Key, l: Lang = lang(), ...args: string[]): string {
  const text = OWN[l]?.[key] ?? LOCALES[l]?.ui[key] ?? OWN.en[key]
  return args.reduce((s, arg, i) => s.replace(`%${i + 1}`, arg), text)
}

/** Messages for VM extensions (the pen), as expected by vm.setLocale. */
export function vmMessages(l: Lang = lang()): Record<string, string> {
  return LOCALES[l]?.pen ?? {}
}

/** BCP-47 tag for speech synthesis. */
export function speechLang(l: Lang = lang()): string {
  const [base, region] = l.split('-')
  return region && region.length === 2 ? `${base}-${region.toUpperCase()}` : base
}
